apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: bedrock-proxy-development

namespace: bedrock-development

resources:
  - ../../base

labels:
  - pairs:
      environment: development
      tier: development

namePrefix: dev-

images:
  - name: bedrock-proxy
    newTag: "dev-latest"

replicas:
  - name: bedrock-proxy
    count: 1

patches:
  # Override ConfigMap data for development
  - target:
      kind: ConfigMap
      name: bedrock-proxy-config
    patch: |-
      - op: replace
        path: /data/AWS_REGION
        value: "us-west-2"
      - op: replace
        path: /data/GIN_MODE
        value: "debug"
      - op: replace
        path: /data/LOG_LEVEL
        value: "debug"
  # Development resource limits (smaller)
  - target:
      kind: Deployment
      name: bedrock-proxy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi

  # Disable HPA in development
  - target:
      kind: HorizontalPodAutoscaler
      name: bedrock-proxy-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

  # Disable VPA in development
  - target:
      kind: VerticalPodAutoscaler
      name: bedrock-proxy-vpa
    patch: |-
      - op: replace
        path: /spec/updatePolicy/updateMode
        value: "Off"

  # Enable debug annotations
  - target:
      kind: Deployment
      name: bedrock-proxy
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/debug.enabled
        value: "true"

  # Development service type
  - target:
      kind: Service
      name: bedrock-proxy-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort