---
# HorizontalPodAutoscaler for bedrock-proxy
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bedrock-proxy-hpa
  namespace: bedrock-system
  labels:
    app: bedrock-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bedrock-proxy
  minReplicas: 3
  maxReplicas: 20
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics for Bedrock-specific scaling
  - type: Pods
    pods:
      metric:
        name: bedrock_proxy_request_duration_seconds
      target:
        type: AverageValue
        averageValue: "2"  # Scale when response time > 2s
  # Request rate-based scaling
  - type: Pods
    pods:
      metric:
        name: bedrock_proxy_requests_per_second
      target:
        type: AverageValue
        averageValue: "50"  # Scale when > 50 RPS per pod
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50          # Scale up by 50% of current replicas
        periodSeconds: 30  # Every 30 seconds
      - type: Pods
        value: 5           # Or add max 5 pods
        periodSeconds: 30
      selectPolicy: Max    # Use the policy that scales up more
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 10          # Scale down by 10% of current replicas
        periodSeconds: 60  # Every minute
      - type: Pods
        value: 2           # Or remove max 2 pods
        periodSeconds: 60
      selectPolicy: Min    # Use the policy that scales down less